version: "3"

vars:
  BINARY: examiner
  MODULE: github.com/pavelanni/examiner
  IMAGE: examiner
  IMAGE_TAG: latest

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  generate:
    desc: Generate Go code from .templ files
    sources:
      - internal/handler/views/*.templ
    generates:
      - internal/handler/views/*_templ.go
    cmds:
      - templ generate

  build:
    desc: Build the binary
    deps: [generate]
    cmds:
      - go build -o {{.BINARY}} ./cmd/examiner/

  run:
    desc: Build and run the server
    deps: [build]
    cmds:
      - ./{{.BINARY}} {{.CLI_ARGS}}

  test:
    desc: Run tests
    deps: [generate]
    cmds:
      - go test ./...

  vet:
    desc: Run go vet
    deps: [generate]
    cmds:
      - go vet ./...

  lint:
    desc: Run golangci-lint
    deps: [generate]
    cmds:
      - golangci-lint run

  image:
    desc: Build container image with Podman
    cmds:
      - podman build -t {{.IMAGE}}:{{.IMAGE_TAG}} .

  image-run:
    desc: Run container locally with Podman (uses Ollama on host)
    deps: [image]
    cmds:
      - podman volume create examiner-data || true
      - >-
        podman run --rm -it
        -p 8080:8080
        -v examiner-data:/data/db:Z
        -v ./questions.json:/data/questions.json:ro,Z
        -e EXAMINER_DB=/data/db/examiner.db
        -e EXAMINER_QUESTIONS=/data/questions.json
        -e EXAMINER_LLM_URL=http://host.containers.internal:11434/v1
        {{.IMAGE}}:{{.IMAGE_TAG}}
        {{.CLI_ARGS}}

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BINARY}}
      - rm -f internal/handler/views/*_templ.go

  tidy:
    desc: Tidy go.mod and go.sum
    cmds:
      - go mod tidy
