version: "3"

vars:
  BINARY: examiner
  MODULE: github.com/pavelanni/examiner
  IMAGE: examiner
  IMAGE_TAG: latest
  REGISTRY: ghcr.io/pavelanni/examiner
  GIT_SHA:
    sh: git rev-parse --short HEAD
  GIT_DIRTY:
    sh: git diff --quiet && echo "" || echo "-dirty"
  DEV_TAG: "{{.GIT_SHA}}{{.GIT_DIRTY}}"
  DEPLOY_HOST: examiner-01
  QUADLET_DIR: .config/containers/systemd

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  generate:
    desc: Generate Go code from .templ files
    sources:
      - internal/handler/views/*.templ
    generates:
      - internal/handler/views/*_templ.go
    cmds:
      - templ generate

  build:
    desc: Build the binary
    deps: [generate]
    cmds:
      - go build -o {{.BINARY}} ./cmd/examiner/

  run:
    desc: Build and run the server
    deps: [build]
    cmds:
      - ./{{.BINARY}} {{.CLI_ARGS}}

  test:
    desc: Run tests
    deps: [generate]
    cmds:
      - go test ./...

  vet:
    desc: Run go vet
    deps: [generate]
    cmds:
      - go vet ./...

  lint:
    desc: Run golangci-lint
    deps: [generate]
    cmds:
      - golangci-lint run

  image:
    desc: Build container image with Podman
    cmds:
      - podman build -t {{.IMAGE}}:{{.IMAGE_TAG}} .

  image-run:
    desc: Run container locally with Podman (uses Ollama on host)
    deps: [image]
    cmds:
      - podman volume create examiner-data || true
      - >-
        podman run --rm -it
        -p 8080:8080
        -v examiner-data:/data/db:Z
        -v ./questions/physics_en.json:/data/questions.json:ro,Z
        -e EXAMINER_DB=/data/db/examiner.db
        -e EXAMINER_QUESTIONS=/data/questions.json
        -e EXAMINER_LLM_URL=http://host.containers.internal:11434/v1
        {{.IMAGE}}:{{.IMAGE_TAG}}
        {{.CLI_ARGS}}

  image-amd64:
    desc: Build x86_64 image for cloud deployment
    cmds:
      - >-
        podman build --platform linux/amd64
        -t {{.REGISTRY}}:{{.DEV_TAG}}
        .
      - echo "Built {{.REGISTRY}}:{{.DEV_TAG}}"

  push:
    desc: Push image to ghcr.io
    cmds:
      - podman push {{.REGISTRY}}:{{.DEV_TAG}}
      - echo "Pushed {{.REGISTRY}}:{{.DEV_TAG}}"

  release:
    desc: Build amd64 image and push to ghcr.io
    cmds:
      - task: image-amd64
      - task: push

  deploy:
    desc: Deploy to cloud host (build, push, update both instances, restart)
    cmds:
      - task: release
      - >-
        ssh {{.DEPLOY_HOST}}
        "sed -i 's|^Image=.*|Image={{.REGISTRY}}:{{.DEV_TAG}}|'
        {{.QUADLET_DIR}}/examiner-en.container
        {{.QUADLET_DIR}}/examiner-ru.container &&
        systemctl --user daemon-reload &&
        systemctl --user restart examiner-en examiner-ru"
      - echo "Deployed {{.DEV_TAG}} to {{.DEPLOY_HOST}} (en + ru)"

  deploy-quick:
    desc: Deploy without rebuilding (use current DEV_TAG)
    cmds:
      - >-
        ssh {{.DEPLOY_HOST}}
        "sed -i 's|^Image=.*|Image={{.REGISTRY}}:{{.DEV_TAG}}|'
        {{.QUADLET_DIR}}/examiner-en.container
        {{.QUADLET_DIR}}/examiner-ru.container &&
        systemctl --user daemon-reload &&
        systemctl --user restart examiner-en examiner-ru"
      - echo "Deployed {{.DEV_TAG}} to {{.DEPLOY_HOST}} (en + ru)"

  deploy-status:
    desc: Check service status on cloud host
    cmds:
      - ssh {{.DEPLOY_HOST}} "systemctl --user status examiner-en examiner-ru"

  deploy-logs:
    desc: Show recent logs from cloud host (LANG=en|ru|all, default all)
    vars:
      LANG: '{{.LANG | default "all"}}'
    cmds:
      - >-
        {{if eq .LANG "en"}}ssh {{.DEPLOY_HOST}} "journalctl --user -u examiner-en -n 50 --no-pager"
        {{else if eq .LANG "ru"}}ssh {{.DEPLOY_HOST}} "journalctl --user -u examiner-ru -n 50 --no-pager"
        {{else}}ssh {{.DEPLOY_HOST}} "journalctl --user -u examiner-en -u examiner-ru -n 50 --no-pager"
        {{end}}

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BINARY}}
      - rm -f internal/handler/views/*_templ.go

  tidy:
    desc: Tidy go.mod and go.sum
    cmds:
      - go mod tidy
